### ISSUE TITLE
Accept script on stdin

### ISSUE THREAD

**Issue by bendoerr** [profburke/troll#3]
The reference implementation allows you to specify a script on stdin. When doing this with `profburke/troll` it causes the program to continuously produce new lines.

**Reference Implementation Example**
```
./torbenm/troll 1 <<< "4d4"
1 2 3 3

```

**Expected**
```
./profburke/troll <<< "4d4"
2 3 3 4

```

**Actual**
```
./profburke/troll <<< "4d4"
<spew of new lines>
^C

```

**Comment by profburke** [comment]
Hah! If I'd realized that the original version accepted rolls from standard input, I might never have bothered writing this one.  

Anyway, I should have this fixed soon.

**Comment by profburke** [comment]
Ok, so it looks like it's a problem with Linenoise-Swift -- which supports command line editing, history, etc. If I remove that and just use Swift's `readLine` then reading from stdin works fine. 

So now the question is do I want to just make use of `readLine` or do I want to try and fix the Linenoise package?
