### ISSUE TITLE
Allow specifying N rolls

### ISSUE THREAD

**Issue by bendoerr** [profburke/troll#4]
The reference implementation allows you to specify the number of times to do the roll for a given script. This does not seem possible with this implementation.

**Reference Implementation Example**
```
./torbenm/troll 3 ./4d4.t
1 3 3 4
1 1 4 4
1 2 4 4

```

**Expected**
```
./profburke/troll 3 ./4d4.t
1 2 3 3
3 4 4 4
2 3 3 3

```

**Actual**
```
./profburke/troll 3 ./4d4.t
[line 1, pos 20] Error: Unexpected character: '_'.
usage: troll [<script> [ID1=N1] [ID2=N2] ... [IDn=Nn]]

```

**Comment by profburke** [comment]
Ok. Not only does it not work, but that's an incredibly useless error. Not surprising if you look at the hack I use to parse the command line.

This, too, ought to be fixable fairly quickly.
